// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwJ_jjnQC98imhdQDf0iqoghyOePt01W4',
    appId: '1:1066263696563:web:8bdb9885abd04dbdfa8cc6',
    messagingSenderId: '1066263696563',
    projectId: 'turfease-a5d3b',
    authDomain: 'turfease-a5d3b.firebaseapp.com',
    storageBucket: 'turfease-a5d3b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZIgi-jRakKpaSUwSnX8Ka_QhNGiQeJRA',
    appId: '1:1066263696563:android:b0626ad85844fc82fa8cc6',
    messagingSenderId: '1066263696563',
    projectId: 'turfease-a5d3b',
    storageBucket: 'turfease-a5d3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIHeZPc7ogDKsxT7OItzYkou-MlByGiqw',
    appId: '1:1066263696563:ios:e76427919609b9e2fa8cc6',
    messagingSenderId: '1066263696563',
    projectId: 'turfease-a5d3b',
    storageBucket: 'turfease-a5d3b.appspot.com',
    iosBundleId: 'com.example.turfease',
  );
}
